=== kwisnia/Projekt_5/public/xml/MovieSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="MovieList.xml" xmlns:proj="MovieList.xml" xmlns:dane="http://www.wiiiiii.pl" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="typyDanych.xsd" namespace="http://www.wiiiiii.pl" />
  <xs:element name="baza_filmow" type="proj:baza_filmowType">
    <xs:key name="gId">
      <xs:selector xpath="proj:gatunki/proj:gatunek" />
      <xs:field xpath="@id" />
    </xs:key>
    <xs:keyref name="gatRef" refer="proj:gId">
      <xs:selector xpath="proj:kolekcja_filmow_oscarowych/proj:film" />
      <xs:field xpath="@idRef" />
    </xs:keyref>
  </xs:element>

  <xs:group name="informacje_dodatkowe">
    <xs:sequence>
      <xs:element type="dane:imieNazwisko" name="autor" />
      <xs:element type="dane:data" name="data_utworzenia" />
      <xs:element type="dane:data" name="data_ostatniej_modyfikacji" />
    </xs:sequence>
  </xs:group>

  <xs:complexType name="gatunekType">
    <xs:simpleContent>
      <xs:extension base="dane:krotkiTekst">
        <xs:attribute type="dane:id" name="id" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="gatunkiType">
    <xs:sequence>
      <xs:element type="proj:gatunekType" name="gatunek" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ocena_rotten_tomatoesType">
    <xs:simpleContent>
      <xs:extension base="dane:ocenaInt">
        <xs:attribute type="dane:jednostka" name="jednostka" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ocena_osobistaType">
    <xs:simpleContent>
      <xs:extension base="dane:ocenaNa10">
        <xs:attribute type="dane:boolean" name="ulubiony" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="box_officeType">
    <xs:simpleContent>
      <xs:extension base="dane:wielkaLiczba">
        <xs:attribute type="dane:jednostka" name="waluta" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:complexType name="lista_oscarowType">
    <xs:sequence>
      <xs:element type="dane:krotkiTekst" name="oscar" maxOccurs="24" minOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="data_premieryType">
    <xs:simpleContent>
      <xs:extension base="dane:data">
        <xs:attribute type="dane:krotkiTekst" name="region" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="daty_premieryType">
    <xs:sequence>
      <xs:element type="proj:data_premieryType" name="data_premiery" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="informacje_o_filmieType">
    <xs:sequence>
      <xs:element type="dane:krotkiTekst" name="tytul" />
      <xs:element type="dane:krotkiTekst" name="org_tytul" />
      <xs:element type="dane:imieNazwisko" name="rezyser" />
      <xs:choice>
        <xs:element type="dane:krotkiTekst" name="kraj_produkcji" />
        <xs:element type="proj:kraje_produkcjiType" name="kraje_produkcji" />
      </xs:choice>
      <xs:element type="dane:ocenaNotInt" name="ocena_na_filmwebie" />
      <xs:element type="proj:ocena_rotten_tomatoesType" name="ocena_rotten_tomatoes" />
      <xs:element type="proj:ocena_osobistaType" name="ocena_osobista" minOccurs="0" maxOccurs="1" />
      <xs:element type="proj:box_officeType" name="box_office" />
      <xs:element type="dane:malaLiczba" name="liczba_oscarow" />
      <xs:element type="proj:lista_oscarowType" name="lista_oscarow" />
      <xs:element name="format_obrazu" type="dane:formatObrazu" />
      <xs:element type="proj:daty_premieryType" name="daty_premiery" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="filmType">
    <xs:sequence>
      <xs:element type="dane:link" name="plakat" />
      <xs:element type="proj:informacje_o_filmieType" name="informacje_o_filmie" />
    </xs:sequence>
    <xs:attribute type="dane:malaLiczba" name="numer_filmu" use="optional" />
    <xs:attribute type="dane:id" name="idRef" use="optional" />
  </xs:complexType>

  <xs:complexType name="krajType">
    <xs:simpleContent>
      <xs:extension base="dane:krotkiTekst"></xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="kraje_produkcjiType">
    <xs:sequence>
      <xs:element type="proj:krajType" name="kraj" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="kolekcja_filmow_oscarowychType">
    <xs:sequence>
      <xs:element type="proj:filmType" name="film" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="informacje_dodatkoweType">
    <xs:group ref="proj:informacje_dodatkowe" />
  </xs:complexType>

  <xs:complexType name="baza_filmowType">
    <xs:sequence>
      <xs:element type="proj:informacje_dodatkoweType" name="informacje_dodatkowe" />
      <xs:element type="proj:gatunkiType" name="gatunki" />
      <xs:element type="dane:krotkiTekst" name="naglowek" />
      <xs:element type="proj:kolekcja_filmow_oscarowychType" name="kolekcja_filmow_oscarowych" />
    </xs:sequence>
    <xs:attribute type="dane:skrot" name="lang" />
  </xs:complexType>

</xs:schema>

=== kwisnia/Projekt_5/public/xml/MovieList.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<baza_filmow lang="PL" xmlns="MovieList.xml" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="MovieList.xml MovieSchema.xsd">
  <informacje_dodatkowe>
    <autor>Kacper Wiśniewski</autor>
    <data_utworzenia>10-10-2020</data_utworzenia>
    <data_ostatniej_modyfikacji>21-01-2021</data_ostatniej_modyfikacji>
  </informacje_dodatkowe>
  <gatunki>
    <gatunek id="g1">Fantasy</gatunek>
    <gatunek id="g2">Dramat</gatunek>
    <gatunek id="g3">Thriller</gatunek>
    <gatunek id="g4">Biograficzny</gatunek>
    <gatunek id="g5">Romans</gatunek>
    <gatunek id="g6">Wojenny</gatunek>
    <gatunek id="g7">Kryminał</gatunek>
    <gatunek id="g8">Dramat historyczny</gatunek>
  </gatunki>
  <naglowek>Kolekcja filmów nagrodzonych Oscarem</naglowek>
  <kolekcja_filmow_oscarowych>
    <film numer_filmu="2" idRef="g2">
      <plakat>https://www.hollywoodawards.com/wp-content/uploads/2018/10/GreenBook-1000x1482.jpg</plakat>
      <informacje_o_filmie>
        <tytul>Green Book</tytul>
        <org_tytul>Green Book</org_tytul>
        <rezyser>Peter Farrelly</rezyser>
        <kraj_produkcji>USA</kraj_produkcji>
        <ocena_na_filmwebie>8.2</ocena_na_filmwebie>
        <ocena_rotten_tomatoes jednostka="%">77</ocena_rotten_tomatoes>
        <ocena_osobista>8/10</ocena_osobista>
        <box_office waluta="$">327900000</box_office>
        <liczba_oscarow>3</liczba_oscarow>
        <lista_oscarow>
          <oscar>Najlepszy film</oscar>
          <oscar>Najlepszy aktor drugoplanowy</oscar>
          <oscar>Najlepszy scenariusz oryginalny</oscar>
        </lista_oscarow>
        <format_obrazu>2.00:1</format_obrazu>
        <daty_premiery>
          <data_premiery region="global">11-09-2018</data_premiery>
          <data_premiery region="pl">25-12-2018</data_premiery>
        </daty_premiery>
      </informacje_o_filmie>
    </film>
    <film numer_filmu="3" idRef="g1">
      <plakat>https://chicagocrusader.com/wp-content/uploads/sites/2/2017/12/SHAPE-OF-WATER2.jpeg</plakat>
      <informacje_o_filmie>
        <tytul>Kształt Wody</tytul>
        <org_tytul>The Shape of Water</org_tytul>
        <rezyser>Guillermo del Toro</rezyser>
        <kraj_produkcji>USA</kraj_produkcji>
        <ocena_na_filmwebie>6.4</ocena_na_filmwebie>
        <ocena_rotten_tomatoes jednostka="%">92</ocena_rotten_tomatoes>
        <ocena_osobista>7/10</ocena_osobista>
        <box_office waluta="$">195300000</box_office>
        <liczba_oscarow>4</liczba_oscarow>
        <lista_oscarow>
          <oscar>Najlepszy film</oscar>
          <oscar>Najlepszy reżyser</oscar>
          <oscar>Najlepsza scenografia</oscar>
          <oscar>Najlepsza muzyka oryginalna</oscar>
        </lista_oscarow>
        <format_obrazu>1.85:1</format_obrazu>
        <daty_premiery>
          <data_premiery region="global">31-07-2017</data_premiery>
          <data_premiery region="pl">16-02-2018</data_premiery>
        </daty_premiery>
      </informacje_o_filmie>
    </film>
    <film numer_filmu="4" idRef="g2">
      <plakat>https://images-na.ssl-images-amazon.com/images/I/91PbfpzX5uL._AC_SL1500_.jpg</plakat>
      <informacje_o_filmie>
        <tytul>Moonlight</tytul>
        <org_tytul>Moonlight</org_tytul>
        <rezyser>Barry Jenkins</rezyser>
        <kraj_produkcji>USA</kraj_produkcji>
        <ocena_na_filmwebie>6.6</ocena_na_filmwebie>
        <ocena_rotten_tomatoes jednostka="%">98</ocena_rotten_tomatoes>
        <ocena_osobista>5/10</ocena_osobista>
        <box_office waluta="$">65300000</box_office>
        <liczba_oscarow>3</liczba_oscarow>
        <lista_oscarow>
          <oscar>Najlepszy film</oscar>
          <oscar>Najlepszy aktor drugoplanowy</oscar>
          <oscar>Najlepszy scenariusz adaptowany</oscar>
        </lista_oscarow>
        <format_obrazu>2.39:1</format_obrazu>
        <daty_premiery>
          <data_premiery region="global">02-09-2016</data_premiery>
          <data_premiery region="pl">17-02-2017</data_premiery>
        </daty_premiery>
      </informacje_o_filmie>
    </film>
    <film numer_filmu="5" idRef="g2">
      <plakat>https://images-na.ssl-images-amazon.com/images/I/71Wp12p6l6L._AC_SY879_.jpg</plakat>
      <informacje_o_filmie>
        <tytul>Spotlight</tytul>
        <org_tytul>Spotlight</org_tytul>
        <rezyser>Tom McCarthy</rezyser>
        <kraj_produkcji>USA</kraj_produkcji>
        <ocena_na_filmwebie>7.6</ocena_na_filmwebie>
        <ocena_rotten_tomatoes jednostka="%">97</ocena_rotten_tomatoes>
        <ocena_osobista>9/10</ocena_osobista>
        <box_office waluta="$">98300000</box_office>
        <liczba_oscarow>2</liczba_oscarow>
        <lista_oscarow>
          <oscar>Najlepszy film</oscar>
          <oscar>Najlepszy scenariusz oryginalny</oscar>
        </lista_oscarow>
        <format_obrazu>1.85:1</format_obrazu>
        <daty_premiery>
          <data_premiery region="global">03-09-2015</data_premiery>
          <data_premiery region="pl">05-02-2016</data_premiery>
        </daty_premiery>
      </informacje_o_filmie>
    </film>
    <film numer_filmu="6" idRef="g2">
      <plakat>https://ih1.redbubble.net/image.1027096256.4377/flat,750x,075,f-pad,750x1000,f8f8f8.jpg</plakat>
      <informacje_o_filmie>
        <tytul>Birdman</tytul>
        <org_tytul>Birdman or (The Unexpected Virtue of Ignorance)</org_tytul>
        <rezyser>Alejandro González Iñárritu</rezyser>
        <kraj_produkcji>USA</kraj_produkcji>
        <ocena_na_filmwebie>7.2</ocena_na_filmwebie>
        <ocena_rotten_tomatoes jednostka="%">91</ocena_rotten_tomatoes>
        <ocena_osobista>9/10</ocena_osobista>
        <box_office waluta="$">103200000</box_office>
        <liczba_oscarow>4</liczba_oscarow>
        <lista_oscarow>
          <oscar>Najlepszy film</oscar>
          <oscar>Najlepszy reżyser</oscar>
          <oscar>Najlepszy scenariusz oryginalny</oscar>
          <oscar>Najlepsze zdjęcia</oscar>
        </lista_oscarow>
        <format_obrazu>1.85:1</format_obrazu>
        <daty_premiery>
          <data_premiery region="global">27-08-2014</data_premiery>
          <data_premiery region="pl">23-01-2015</data_premiery>
        </daty_premiery>
      </informacje_o_filmie>
    </film>
    <film numer_filmu="7" idRef="g4">
      <plakat>https://www.goldenglobes.com/sites/default/files/articles/cover_images/2014-12-years-a-slave_0.jpg</plakat>
      <informacje_o_filmie>
        <tytul>Zniewolony. 12 Years A Slave</tytul>
        <org_tytul>12 Years a Slave</org_tytul>
        <rezyser>Steve McQueen</rezyser>
        <kraj_produkcji>USA</kraj_produkcji>
        <ocena_na_filmwebie>7.5</ocena_na_filmwebie>
        <ocena_rotten_tomatoes jednostka="%">95</ocena_rotten_tomatoes>
        <ocena_osobista>5/10</ocena_osobista>
        <box_office waluta="$">187700000</box_office>
        <liczba_oscarow>3</liczba_oscarow>
        <lista_oscarow>
          <oscar>Najlepszy film</oscar>
          <oscar>Najlepsza aktorka drugoplanowa</oscar>
          <oscar>Najlepszy scenariusz adaptowany</oscar>
        </lista_oscarow>
        <format_obrazu>2.39:1</format_obrazu>
        <daty_premiery>
          <data_premiery region="global">30-08-2013</data_premiery>
          <data_premiery region="pl">31-01-2014</data_premiery>
        </daty_premiery>
      </informacje_o_filmie>
    </film>
    <film numer_filmu="8" idRef="g3">
      <plakat>https://images-na.ssl-images-amazon.com/images/I/91ZzxXt17zL._AC_SL1500_.jpg</plakat>
      <informacje_o_filmie>
        <tytul>Operacja Argo</tytul>
        <org_tytul>Argo</org_tytul>
        <rezyser>Ben Affleck</rezyser>
        <kraj_produkcji>USA</kraj_produkcji>
        <ocena_na_filmwebie>7.3</ocena_na_filmwebie>
        <ocena_rotten_tomatoes jednostka="%">96</ocena_rotten_tomatoes>
        <ocena_osobista>7/10</ocena_osobista>
        <box_office waluta="$">232300000</box_office>
        <liczba_oscarow>3</liczba_oscarow>
        <lista_oscarow>
          <oscar>Najlepszy film</oscar>
          <oscar>Najlepszy montaż</oscar>
          <oscar>Najlepszy scenariusz adaptowany</oscar>
        </lista_oscarow>
        <format_obrazu>2.39:1</format_obrazu>
        <daty_premiery>
          <data_premiery region="global">31-08-2012</data_premiery>
          <data_premiery region="pl">30-11-2012</data_premiery>
        </daty_premiery>
      </informacje_o_filmie>
    </film>
    <film numer_filmu="9" idRef="g5">
      <plakat>https://images-na.ssl-images-amazon.com/images/I/61vEXxfSfiL._AC_SL1500_.jpg</plakat>
      <informacje_o_filmie>
        <tytul>Artysta</tytul>
        <org_tytul>The Artist</org_tytul>
        <rezyser>Michel Hazanavicius</rezyser>
        <kraj_produkcji>USA/Belgia/Francja</kraj_produkcji>
        <ocena_na_filmwebie>7.5</ocena_na_filmwebie>
        <ocena_rotten_tomatoes jednostka="%">95</ocena_rotten_tomatoes>
        <ocena_osobista>8/10</ocena_osobista>
        <box_office waluta="$">133400000</box_office>
        <liczba_oscarow>5</liczba_oscarow>
        <lista_oscarow>
          <oscar>Najlepszy film</oscar>
          <oscar>Najlepszy reżyser</oscar>
          <oscar>Najlepszy aktor pierwszoplanowy</oscar>
          <oscar>Najlepsza muzyka oryginalna</oscar>
          <oscar>Najlepsze kostiumy</oscar>
        </lista_oscarow>
        <format_obrazu>1.33:1</format_obrazu>
        <daty_premiery>
          <data_premiery region="global">15-05-2011</data_premiery>
          <data_premiery region="pl">10-02-2012</data_premiery>
        </daty_premiery>
      </informacje_o_filmie>
    </film>
    <film numer_filmu="10" idRef="g4">
      <plakat>https://images-na.ssl-images-amazon.com/images/I/81IqfwgR1vL._AC_SL1500_.jpg</plakat>
      <informacje_o_filmie>
        <tytul>Jak zostać królem</tytul>
        <org_tytul>The King's Speech</org_tytul>
        <rezyser>Tom Hooper</rezyser>
        <kraj_produkcji>USA/Wielka Brytania/Australia</kraj_produkcji>
